#!/bin/sh
set -e

apt-get update

apt-get install -y --no-install-recommends \
        software-properties-common \
        apt-transport-https

apt-add-repository ppa:fish-shell/release-2
apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-trusty main'

apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 \
            --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

apt-get update

apt-get install -y --no-install-recommends \
        build-essential \
        curl \
        docker-engine \
        fish \
        git \
        libevent-dev \
        libncurses5-dev \
        libxml2-utils \
        unzip \
        ruby \
        silversearcher-ag \
        ssh \
        time \
        vim \
        wget

apt-get clean

curl -L https://github.com/docker/compose/releases/download/1.5.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

