#!/bin/sh
set -e

curl -L https://github.com/tmux/tmux/releases/download/$TMUX_VERSION/tmux-$TMUX_VERSION.tar.gz \
     -o /tmux.tar.gz

tar xfz /tmux.tar.gz

cd /tmux-$TMUX_VERSION
./configure && make && make install
cd /
rm -r /tmux-$TMUX_VERSION
rm /tmux.tar.gz

gem install --no-rdoc --no-ri tmuxinator

