#!/bin/sh
set -e

apt-get install -y --no-install-recommends python

curl -L https://s3.amazonaws.com/aws-cli/awscli-bundle.zip \
     -o /awscli.zip

unzip awscli.zip

./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

rm -r /awscli-bundle
rm awscli.zip

