#!/bin/sh
set -e

apt-get update

apt-get install -y --no-install-recommends \
        software-properties-common \
        apt-transport-https

apt-add-repository ppa:fish-shell/release-2
apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-trusty main'

apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 \
            --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

apt-get update

apt-get install -y --no-install-recommends \
        build-essential \
        libevent-dev=2.0.21-stable-1ubuntu1.14.04.1 \
        libncurses5-dev=5.9+20140118-1ubuntu1 \
        ssh=1:6.6p1-2ubuntu2.3 \
        wget=1.15-1ubuntu1.14.04.1 \
        curl=7.35.0-1ubuntu2.5 \
        git=1:1.9.1-1ubuntu0.1 \
        docker-engine=1.9.0-0~trusty \
        fish=2.2.0-1~trusty \
        vim=2:7.4.052-1ubuntu3 \
        silversearcher-ag=0.19.2-1 \
        time=1.7-24 \
        libxml2-utils=2.9.1+dfsg1-3ubuntu4.7

apt-get clean

curl -L https://github.com/docker/compose/releases/download/1.5.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

