set t_Co=256

execute pathogen#infect()
syntax on
filetype plugin indent on

colorscheme wombat256

map <silent> <LocalLeader>nt :NERDTreeToggle<CR>
map <silent> <LocalLeader>nr :NERDTree<CR>
map <silent> <LocalLeader>ch :HighlightColumnAdd<CR>
map <silent> <LocalLeader>co :HighlightColumnOne<CR>
map <silent> <LocalLeader>cc :HighlightColumnOff<CR>
map <silent> <LocalLeader>a :CtrlP<CR>

let g:ctrlp_user_command='ag %s -l --nocolor -g ""'
let g:ctrlp_use_caching=0

set number
set shiftwidth=2
set tabstop=2
set expandtab
set nowrap
set incsearch
set hlsearch

silent !mkdir -p /tmp/vim
set dir=/tmp/vim//
