set t_Co=256

execute pathogen#infect()
syntax on
filetype plugin indent on

colorscheme wombat256

map <silent> <LocalLeader>nt :NERDTreeToggle<CR>
map <silent> <LocalLeader>nr :NERDTree<CR>
map <silent> <LocalLeader>ch :HighlightColumnAdd<CR>
map <silent> <LocalLeader>co :HighlightColumnOne<CR>
map <silent> <LocalLeader>cc :HighlightColumnOff<CR>
map <silent> <LocalLeader>a :CtrlP<CR>

let g:ctrlp_user_command='ag %s -l --nocolor -g ""'
let g:ctrlp_use_caching=0

set number
set shiftwidth=2
set tabstop=2
set expandtab
set nowrap
set incsearch
set hlsearch

silent !mkdir -p /tmp/vim
set dir=/tmp/vim//

" Highlight trailing whitespace
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd BufRead,InsertLeave * match ExtraWhitespace /\s\+$/
" Set up highlight group & retain through colorscheme changes
highlight ExtraWhitespace ctermbg=88 guibg=red
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=88 guibg=red

" Highlight too-long lines
autocmd BufRead,InsertEnter,InsertLeave * 2match LineLengthError /\%76v.*/
highlight LineLengthError ctermbg=58 guibg=gold4
autocmd ColorScheme * highlight LineLengthError ctermbg=58 guibg=gold4
